name: Ping Repetify URL

on:
  schedule:
    # Runs every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Call Repetify Login URL and Log Response
        run: |
          curl -s -f -L \
          -x "${{ secrets.WEBSHARE_PROXY_URL }}" \
          -o /dev/null \
          -w "HTTP-Status: %{http_code}\n" \
          "https://repetify.lorenzboss.com/users/sign_in"
